### ISSUE TITLE
( Addon Activation Error )

### ISSUE THREAD

**Issue by A16D** [MyHighLow/Quick_Bools#1]
After sucessfully installing Addon,
When we try to activate the addon, it retuen the follwoing Error {Scrrenshot} 
![Snipaste_2022-12-20_19-16-35](https://user-images.githubusercontent.com/103478102/208682182-d1432f4b-7f05-4710-8e33-0ddd73ef20ac.png)

**Comment by MyHighLow** [comment]
Whoops! Seems like I hard-coded a path in there. Should be fixed now!
